name: 'Deploy'

on:
  push:
    branches: [main]

env:
  ASTRO_TELEMETRY_DISABLED: 1

jobs:
  check:
    name: Format Check + Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true # github pages artifact needs the actual assets from git lfs
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run check
      - run: npm run format:check
      - run: npm run build
      - run: touch dist/.nojekyll # tell github pages to not use jekyll
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: dist

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run test

  deploy:
    name: Deploy
    needs: [check, test]

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    concurrency: deploy-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
